### PR TITLE
Camel endpoint for SMSlib v4

### PR DESCRIPTION
**Pull request by derjust**
Hi!

This pull request contains the following additions:
- Basic implementation of a Apache Camel endpoint
  - Endpoint can be modem or mock based gateways
  - All incoming messages are mapped to Camel Exchanges and all headers are preserved
  - Outgoing messages are supported but quite bare (Just send the Exchange's body as string - that's it)

This pull request contains the following changes:
- Added optional dependencies for RXTX/java comm to help users to find the correct dependencies
  - "Replaced" RXTX dependency with https://code.google.com/p/nrjavaserial/
  - Compile compatible with RXTX but does the native library loading on-the-fly during runtime (extract to temp folder)
- Refactored mock test gateway to also send messages (for Camel endpoint testing)
- Improved reflection code for javax.comm calls to preserve complete stacktraces

Let me know if you have any questions,
Sebastian

### CODE REVIEW

**Comment by tdelenikas** [comment]
Sebastian,

Is this normal???

```
[DEBUG] Retrieving parent-POM: org.apache:apache:pom:9 for project: org.apache.felix:felix-parent:pom:2.1 from the repository.
[DEBUG] Plugin dependencies for:

org.apache.felix:maven-bundle-plugin:2.3.7

are:

biz.aQute:bndlib:jar:1.50.0:runtime
org.apache.felix:org.apache.felix.bundlerepository:jar:1.6.6:runtime
org.apache.maven:maven-core:jar:2.0.7:runtime
org.apache.maven:maven-archiver:jar:2.4.1:runtime
org.apache.maven.shared:maven-dependency-tree:jar:1.2:runtime
org.codehaus.plexus:plexus-utils:jar:2.1:runtime


[DEBUG] org.apache.felix:maven-bundle-plugin:maven-plugin:2.3.7:runtime (selected for runtime)
[WARNING] POM for 'biz.aQute:bndlib:pom:1.50.0:runtime' is invalid.

Its dependencies (if any) will NOT be available to the current build.
```

**Comment by derjust** [comment]
Hi T,

I can't really reproduce the issue. In which module does it appear?
Which goals did you execute?

At least the camel-stuff is unrelated to OSGi - I think.

**Comment by tdelenikas** [comment]
I'll proceed with the merge. I still get this warning:

```
[WARNING] POM for 'biz.aQute:bndlib:pom:1.50.0:runtime' is invalid.
Its dependencies (if any) will NOT be available to the current build.
```

but I'll push in the the `dev` branch for you to use and we will see how it goes...

**Comment by derjust** [comment]
OK
Will try to check tomorrow.
What env do you use while getting the warning?

Sebastian

**Comment by tdelenikas** [comment]
This warning pops up during the standard "mvn compile/package/..." phase.
I run on Win7/x64, JDK1.7.0_45, Maven 2.2.1

**Comment by derjust** [comment]
OK
Is mvn 2 intentionally?
Any plans going to 3?

**Comment by tdelenikas** [comment]
Not really intentional, but this is what I currently use.
FYI, on my Ubuntu VM / Maven 3.0.5, this warning does _not_ pop up.

**Comment by derjust** [comment]
Hi!

yeah also with my 3.0.. it works on Windows.
Therefore my question how much effort is required to support Maven2 :)

Cheers,
Sebastian

**Comment by derjust** [comment]
Hi!

I digged a little bit to identify the issue.

The issue itself was also raised within bndtool but was closed without 
further action:
https://github.com/bndtools/bnd/issues/119

It is caused by an "invalid" POM. Version 1.50 
repo1.maven.org/maven2/biz/aQute/bndlib/1.50.0/bndlib-1.50.0.pom
starts this way (don't be confused by your browser, download the file to 
double-check)
   <modelVersion>
     4.0.0
   </modelVersion>

This newlines seem to be incompatible with Maven 2.
Maven3 (Windows and Linux) seem to be just happy with it.

"Fixing" the POM  in the local repository to
   <modelVersion>4.0.0</modelVersion>
also makes the warning to disappear.

As I have no idea about this OSGi/bnd-stuff: Is moving to bndlib 2.0 an 
option? It does not have those strange newlines.

Also as mvn2 is EOL:
http://maven.apache.org/maven-2.x-eol.html
Might it be worth to accept this behavoir/encourage everyone to use 
Maven3?

Regards,
Sebastian

**Comment by tdelenikas** [comment]
Screw it, lets switch to v3.

**Pull request merged**
